import PageTransiton from "@/components/PageTransition";
import SideBar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PageTransiton>
          {children}

          <Toaster
            position="bottom-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: "#374151",
                color: "#ffffff",
                borderRadius: "8px",
                padding: "12px 16px",
                fontSize: "14px",
                fontWeight: "500",
                boxShadow: "0 10px 25px rgba(0, 0, 0, 0.2)",
                border: "1px solid #4B5563",
              },
              success: {
                style: {
                  background: "#059669",
                  color: "#ffffff",
                },
              },
              error: {
                style: {
                  background: "#DC2626",
                  color: "#ffffff",
                },
              },
            }}
          />
        </PageTransiton>
      </body>
    </html>
  );
}
